## The functions in this file invert a matrix and cache the
## inverse for later use. These are part of Assignment 2 for
## Dr. Roger Peng's Coursera on R.

## makeCacheMatrix takes in an invertible matrix X, calculates
## the inverse, and caches it. That cached matrix inverse can
## then be summoned using the cacheSolve function.

makeCacheMatrix <- function(x = matrix()) {
     m <- NULL
     set <- function(y) {
          x <<- y
          m <<- NULL
     }
     get <- function() x
     setinv <- function(solve) m <<- solve
     getinv <- function() m
     list(set = set, get = get,
          setinv = setinv,
          getinv = getinv)
}


## cacheSolve takes in a list of the type generated by
## the function makeCacheMatrix. Within that list, the
## inverse of the matrix may have already been computed.
## If not, the inverse will be calculated; if so, the
## cached matrix inverse will be returned.

cacheSolve <- function(x, ...) {
        ## Return a matrix that is the inverse of 'x'
     m <- x$getinv()
     if(!is.null(m)) {
          message("getting cached matrix inverse")
          return(m)
     }
     data <- x$get()
     m <- solve(data, ...)
     x$setinv(m)
     m
     
}
